from typing import List, Protocol, Optional, Any

from estimania.player import Player

class GameEvents(Protocol):
    def round_announce(self, text: str) -> None: ...
        
    def score(self, players: List[Player]) -> None: ...
    
    def turn_of(self, player: Player) -> None:  ...

    def table(self, cards_str: List[str], names: List[str]) -> None: ...
    
    def trick_winner(self, highest_card: Any) -> None: ...

    def final_scores(self, players: List[Player]) -> None: ...

    def error(self, player: Player, message: str) -> None: ...

    def private_table(self, viewer: Player, cards_str: List[str], other_players: List[Player]) -> None: ...